### ISSUE TITLE
Error on using color functions on @mdb-text-color-light

### ISSUE THREAD

**Issue by EhsanCh** [FezVrasta/bootstrap-material-design#1122]
In  bootstrap-material-design/less/_variables.less  Line 5

@mdb-text-color-light: ~"rgba(@{rgb-white}, 0.84)";

This cause that we can not use this variable in color functions like mix , lighten and ...

**Comment by FezVrasta** [comment]
closing since the issues template has not been respected. feel free to re-open following the rules. Thank you.
