### ISSUE TITLE
Ripple Not Working In Navbar Brand and Link

### ISSUE THREAD

**Issue by mfauzanf** [FezVrasta/bootstrap-material-design#1126]
#### Test Case 
(http://codepen.io/rosskevin/pen/VvRgrN ) 

#### Summary
Ripple Not Working in Navbar Brand, Link , etc but only working in Search Box. I use the codepen test but it works in codepen. I also have put $.material.init(); I dont know what's wrong.

Here's the screenshot of the test case

![working](https://cloud.githubusercontent.com/assets/16166948/20546270/b32a3df0-b146-11e6-83b4-1851fae32286.png)

Here's the screenshot of the code 

![image](https://cloud.githubusercontent.com/assets/16166948/20546303/d02e60fc-b146-11e6-8647-5e366aa76999.png)

Here's the code if you need 
http://pastebin.com/6iRCEczh

Thank You and Sorry for the inconvenience

**Comment by FezVrasta** [comment]
the code pen test case should be modified to show your problem

**Comment by mfauzanf** [comment]
![working](https://cloud.githubusercontent.com/assets/16166948/20556701/d70dbd88-b19a-11e6-98d0-660b5b327ca2.png)

I modify the codepen and ripple works on codepen but still dont work on me. Please Help

**Comment by FezVrasta** [comment]
then it's a problem on your end. try seeking for help in stackoverflow
